# Generated by Django 3.0 on 2020-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0002_auto_20191218_0527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
