# Generated by Django 3.0 on 2020-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0003_auto_20200312_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_mobile', models.CharField(max_length=15)),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
