# Generated by Django 3.0 on 2020-03-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0005_employeevisit_visitlog_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='vis_photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/'),
        ),
    ]
