# Generated by Django 3.0.3 on 2020-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0006_auto_20200325_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='footcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'month',
            },
        ),
    ]
