# Generated by Django 3.0.3 on 2020-04-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0007_footcount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='footcount',
            table='footcount',
        ),
    ]
