# Generated by Django 3.0.3 on 2020-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0008_auto_20200417_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='footcount',
            name='count',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footcount',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
