# Generated by Django 3.0 on 2020-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0009_auto_20200418_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='vis_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='vis_photo_file',
            field=models.FileField(default=None, null=True, upload_to='Visitors/'),
        ),
        migrations.AlterField(
            model_name='footcount',
            name='count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='footcount',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
