# Generated by Django 3.0 on 2020-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcount', '0010_auto_20200515_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='vis_email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
    ]
